### ISSUE TITLE
run error with UnrealCV example

### ISSUE THREAD

**Issue by Dongzhou-1996** [whluo/active_tracking_drl#1]
Is the commands provided for UnrealCV example in README.md false? (--env-id Active-Tracking-Discrete-v0), it may be in format like 'UnrealTrack-City1StefaniPath1-DiscreteColor-v1'. And would you like list the environment binaries of UnrealCV depended for this project?

kindly regards,
dong zhou

**Comment by Tie-1** [comment]
I meet this question too! Have you solved this problem？Can you give me some advice？
kindly regards,
zhao tie

**Comment by Dongzhou-1996** [comment]
> I meet this question too! Have you solved this problem？Can you give me some advice？ kindly regards, zhao tie

I had figured it out, you can see the closed [issue](https://github.com/zfw1226/gym-unrealcv/issues/19) and refer to [gym-unrealcv project](https://github.com/zfw1226/gym-unrealcv).

**Comment by hzt-1999** [comment]
Your help was very much appreciated! I will check it out later. Thank you again for your helping!
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "whluo/active_tracking_drl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月21日(星期一) 上午9:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [whluo/active_tracking_drl] run error with UnrealCV example (#1)





  
I meet this question too! Have you solved this problem？Can you give me some advice？ kindly regards, zhao tie
  
I had figured it out, you can see the closed issue and refer to gym-unrealcv project.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hzt-1999** [comment]
尊敬的DongZhou：

&nbsp; &nbsp;您好！我是西北工业大学大四的一名学生，我的毕设想复现2019年发表在TPAMI的《End-to-end Active Object Tracking and Its Real-world Deployment via Reinforcement Learning》这篇文章。目前我在做ViZDoom仿真部分，我看您在Run errors with gym-unrealcv for active object tracking · Issue #19 · zfw1226/gym-unrealcv (github.com)中说到您成功地在ViZDoom下实现效果，所以想请教您一些基础的问题，我按照openai/universe-starter-agent: A starter agent that can solve a number of universe environments. (github.com)设置了依赖关系，根据whluo/active_tracking_drl (github.com)下运行程序，但是目前出现了如下报错，不知所措。希望您能够指点一二，不胜感激！

&nbsp; &nbsp;期盼您的回信！万念感激！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "whluo/active_tracking_drl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月21日(星期一) 上午9:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [whluo/active_tracking_drl] run error with UnrealCV example (#1)





  
I meet this question too! Have you solved this problem？Can you give me some advice？ kindly regards, zhao tie
  
I had figured it out, you can see the closed issue and refer to gym-unrealcv project.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Dongzhou-1996** [comment]
> 尊敬的DongZhou： &nbsp; &nbsp;您好！我是西北工业大学大四的一名学生，我的毕设想复现2019年发表在TPAMI的《End-to-end Active Object Tracking and Its Real-world Deployment via Reinforcement Learning》这篇文章。目前我在做ViZDoom仿真部分，我看您在Run errors with gym-unrealcv for active object tracking · Issue #19 · zfw1226/gym-unrealcv (github.com)中说到您成功地在ViZDoom下实现效果，所以想请教您一些基础的问题，我按照openai/universe-starter-agent: A starter agent that can solve a number of universe environments. (github.com)设置了依赖关系，根据whluo/active_tracking_drl (github.com)下运行程序，但是目前出现了如下报错，不知所措。希望您能够指点一二，不胜感激！ &nbsp; &nbsp;期盼您的回信！万念感激！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "whluo/active_tracking_drl" ***@***.***&gt;; 发送时间:&nbsp;2022年3月21日(星期一) 上午9:20 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [whluo/active_tracking_drl] run error with UnrealCV example (#1) I meet this question too! Have you solved this problem？Can you give me some advice？ kindly regards, zhao tie I had figured it out, you can see the closed issue and refer to gym-unrealcv project. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

具体报错是什么？我这边看不到。
PS：VizDoom Env比较好复现，Unreal Env比较难收敛。

**Comment by Tie-1** [comment]
不好意思大佬，可能刚刚显示有问题，现在我将报错信息粘贴如下：
运行python train.py --num-workers=2 --env-id=TrackObjSmallMazeRandFlip-v2 --log-dir=save/to --max-global-steps=29999 --val-model-secs=30 --max-val-episodes=2，出现：
Executing the following commands:
mkdir -p save/to
echo /home/dell/anaconda3/envs/tracker/bin/python train.py --num-workers=2 --env-id=TrackObjSmallMazeRandFlip-v2 --log-dir=save/to --max-global-steps=29999 --val-model-secs=30 --max-val-episodes=2 &gt; save/to/cmd.sh
kill $( lsof -i:12345 -t ) &gt; /dev/null 2&gt;&amp;1
kill $( lsof -i:12222-12224 -t ) &gt; /dev/null 2&gt;&amp;1
tmux kill-session -t a3c
tmux new-session -s a3c -n ps -d bash
tmux new-window -t a3c -n w-0 bash
tmux new-window -t a3c -n w-1 bash
tmux new-window -t a3c -n w-val bash
tmux new-window -t a3c -n tb bash
tmux new-window -t a3c -n htop bash
sleep 1
tmux send-keys -t a3c:ps 'CUDA_VISIBLE_DEVICES= /home/dell/anaconda3/envs/tracker/bin/python worker.py --log-dir save/to --env-id TrackObjSmallMazeRandFlip-v2 --model-id convx2lstm --num-workers 2 --max-global-steps 29999 --lr 0.0001 --ent-factor 0.01 --egreedy -1.0 --explore-factor 1.0 --job-name ps' Enter
tmux send-keys -t a3c:w-0 'CUDA_VISIBLE_DEVICES=0 /home/dell/anaconda3/envs/tracker/bin/python worker.py --log-dir save/to --env-id TrackObjSmallMazeRandFlip-v2 --model-id convx2lstm --num-workers 2 --max-global-steps 29999 --lr 0.0001 --ent-factor 0.01 --egreedy -1.0 --explore-factor 1.0 --job-name worker --task 0 --remotes 1' Enter
sleep 10
tmux send-keys -t a3c:w-1 'CUDA_VISIBLE_DEVICES=0 /home/dell/anaconda3/envs/tracker/bin/python worker.py --log-dir save/to --env-id TrackObjSmallMazeRandFlip-v2 --model-id convx2lstm --num-workers 2 --max-global-steps 29999 --lr 0.0001 --ent-factor 0.01 --egreedy -1.0 --explore-factor 1.0 --job-name worker --task 1 --remotes 1' Enter
sleep 10
tmux send-keys -t a3c:w-val '/home/dell/anaconda3/envs/tracker/bin/python worker.py --log-dir save/to --env-id TrackObjSmallMazeRandFlip-v2 --model-id convx2lstm --num-workers 2 --max-global-steps 29999 --lr 0.0001 --ent-factor 0.01 --egreedy -1.0 --explore-factor 1.0 --job-name worker_val --task 2 --val-model-secs 30 --max-val-episodes 2 --val-criterion score --env-val-id TrackObjSmallMazeRandFlip-v2' Enter
sleep 10
tmux send-keys -t a3c:tb 'tensorboard --logdir save/to --port 12345' Enter
tmux send-keys -t a3c:htop htop Enter


Use `tmux attach -t a3c` to watch process output
Use `tmux kill-session -t a3c` to kill the job
Point your browser to http://localhost:12345 to see Tensorboard






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "whluo/active_tracking_drl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月21日(星期一) 晚上9:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [whluo/active_tracking_drl] run error with UnrealCV example (#1)





  
尊敬的DongZhou： &nbsp; &nbsp;您好！我是西北工业大学大四的一名学生，我的毕设想复现2019年发表在TPAMI的《End-to-end Active Object Tracking and Its Real-world Deployment via Reinforcement Learning》这篇文章。目前我在做ViZDoom仿真部分，我看您在Run errors with gym-unrealcv for active object tracking · Issue #19 · zfw1226/gym-unrealcv (github.com)中说到您成功地在ViZDoom下实现效果，所以想请教您一些基础的问题，我按照openai/universe-starter-agent: A starter agent that can solve a number of universe environments. (github.com)设置了依赖关系，根据whluo/active_tracking_drl (github.com)下运行程序，但是目前出现了如下报错，不知所措。希望您能够指点一二，不胜感激！ &nbsp; &nbsp;期盼您的回信！万念感激！
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "whluo/active_tracking_drl" @.&gt;; 发送时间:&nbsp;2022年3月21日(星期一) 上午9:20 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [whluo/active_tracking_drl] run error with UnrealCV example (#1) I meet this question too! Have you solved this problem？Can you give me some advice？ kindly regards, zhao tie I had figured it out, you can see the closed issue and refer to gym-unrealcv project. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: @.***&gt;
  
具体报错是什么？我这边看不到。
 PS：VizDoom Env比较好复现，Unreal Env比较难收敛。
